language: node_js
sudo: false
script:
- npm test
deploy:
  provider: npm
  email: ryan@ryanbreen.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: N5Xu1GdCVfi2FcXqck09BR9ko3Kki/D9aC0XgncsOja8rIN6ojMwcbnSU/tBUVFVUS48rNwFP5ta91Az9FFQEmAQa4vIyTB4XA9h4jKCFBylJtH89SlxBMK6UPndCL9e8A1jDroJRkkVnIWVfcol5xrLP01w0FIoJVg7OFfZLP8=
env:
  secure: C0ckzQRF2q/ogE0Pn9jx/mRXPG96652/zoIc3cg1OZ2xDlM5C8ne5JJYWy8c+9J4LRexq24CxQmE8SFpNKDNJUKMlWXscmEo7S8fYNaceso5F0BijIovy5Wnh2uE/GyL/+fOEjVJZ3BndZlgFzWxFUmTHdgUqs3ucCEPnmS0pyG2ItNj+/V82X6LG6rKghfIN1lxJyfJKi+iUtRESIonHqvaLE8S1ZNxUlxMW7NHwZUoy7orjEoqx5ZAXBz6zmztOXyuxio0kBeLwb57V+XPjFrqyiyGXI239DvGz6mT8xpP92s/WnUYADPM9mW6FA803aHbdk/4Rzq9zOHmY4w76ZXP6zM363xDjKGk4kf8/vndHiQGJr4RE+HGdL87ischW3WZG5ytMo39Ydu3J/aBMTp4kIOEz6UZoSRw6P2grwHMd1oOgHhGRekPY8Lr7nBSWq17mp+cxVFSw8egBsNRxEa1EPe9qQGaA61DHTH0YHoE7o3QZhTTZWmXUtSOSHL+jmVMZERKKc5gVJfHOkTXhPgwkJjfN5UOrntjvypLGp07L2egl2DqnoIQrA0utbz1RpdocnXk8SjOiq1QDpcogDI2QotS7cHQuNmb93LRa8P2dmQiV3AHYog7tSC2HVluWJFdj+TzoKL9DY05/thmt8EwUYwoGNbo8ijFnWu+pSE=
