language: node_js
sudo: false
script:
- npm test
deploy:
  provider: npm
  email: ryan@ryanbreen.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: N5Xu1GdCVfi2FcXqck09BR9ko3Kki/D9aC0XgncsOja8rIN6ojMwcbnSU/tBUVFVUS48rNwFP5ta91Az9FFQEmAQa4vIyTB4XA9h4jKCFBylJtH89SlxBMK6UPndCL9e8A1jDroJRkkVnIWVfcol5xrLP01w0FIoJVg7OFfZLP8=
env:
  secure: NsLVAu7u9d9gTXwl5BV5xxp6VJP1uVn6iodjQVV4jt9n9LvrlEcXfp7gIKKzuxGMKRlaJprdnwa0zYnm+0jquzULOW1KazrH1RkD4OQBZUceOJvoL2HcFV/hgYwygaQYdxAG5tYPcyBhjQzDhwKvVvLwGfZX7YXZV9g2yCqF7DGm3fcgNIk3rrXuKHipzSYCsgGghGkuf1QrA8Lg/aQ6HmD1ZbTd5fJCxIsYIMXLW/v+74WZjeDa/fntU47XJC+aXXCw8m18BFmcx+MiszTkZAEQOGiKNw6ROj76m/QDyHypU/S8RpQLDEmcCNfQ5hEi/yOsfatkt/TNIjaB95R3dKVqd5ytVEUbUC4NAzbbZjPFb154eN4wqDoaObdtumufwD8uFVSwtpvewEXBcvTbT7naLVaQY5pZmbEh/TLxmnZbGnL4DKsjcqahO+o2WsbmMoHqmwTNZSlA5K0doUQr5nX7EpGYd8wEMTJqwsrVMg7d0g33sFIDzpknhuljXTDOmLhPZsrV0RkjJfN9u0rgKKJ6tdlG2c90VGh8/sJnNTm/dbY01+2YhyhE5cHkauwQUq1is/yCOhDO6P2Ce6xKeAOaET1hfjUyYYUAr3NlPM8Og8iD0PAlVO9hQ7WB175AtRb9KyHPKNHHC+5sox/usjYx7T07i5GIHgojNGMwAiQ=
  global:
    secure: TP4GAaGoVjCA0SfZrwEDMUIHbYydRAQy6A/MsatYaYWdOrEw/LJD/9zDZ4s+1N1jFyw/CNYiz6zGrecjuxn8vIG3vLdoV6PRPgLlafHgsrcgZHQazpO7z9+1gbg5jUOgvkDoXBxWeGg0tSOyouPn0Jd7tsVoyy3zGZP2Fj6w1J0Gt/2v3cU0pDKkYpUxgqWXEIeJLBbKH0sgTKIPDPXIASKbbp7lFFlidt9ff4L5NtzIsorsp8zElWMcbctHlEjsCgqRfy2mI9mV2PkZ3XGlQteeGkXQ3I/JNgfMGBOqKb2iOh2v9BN5daRDHrh6d0qOjw3GLkmJcacU4tAV6vLTIS+gDWr2yBE2uSecpsMb2/g8iHJtB4HhM0fAYnNsO38IkkegTg3T66KPnCcnFIXpcG/bD309vysiDltDJAjbLDuLJ0mBgLfOaqy/WV3aojU72Y0uy5YDmSRonwEL0K/JwSpsGu7n4V8q7P2TnPmjvtUvVN3/EYqM+xlcWTWybD1a1FZUyXHku0W/a9qH3V4Ka7QghGUwaHpvQ8KUoO1mt26BHqB/uPbBu7kDC/f355lVdt+bmze+ASXaxjqa6afyMofyUK+YLmXVdaWREB/XhHtXPoLuj6PF4Gp2jEUhSpaIK2Cf9kIcbFRvWAmZqSuZLzuu1jnysVDiRLu/AlSkIR4=
